import json
import sys
from datetime import datetime


def main() -> int:
    try:
        with open('docs/data/latest_forecast.json', 'r') as f:
            data = json.load(f)

        current = data.get('current_price', 0) or 0
        ensemble = (
            data.get('predictions', {})
            .get('models', {})
            .get('ensemble') or [0]
        )
        trend = (
            data.get('insights', {})
            .get('trend', {})
            .get('direction', 'Unknown')
        )

        print('🤖 Daily forecast update ' + datetime.utcnow().strftime('%Y-%m-%d'))
        print()
        print(f'📊 Current: ${current:.2f}')
        if ensemble and ensemble[0] is not None:
            print(f'🔮 Tomorrow: ${float(ensemble[0]):.2f}')
        print(f'📈 Trend: {trend}')
        print()
        print('Generated by automated ML pipeline')
        return 0
    except Exception as e:  # noqa: BLE001
        print(f'🤖 Daily forecast update (error getting details: {e})')
        return 0


if __name__ == '__main__':
    sys.exit(main())
